# Generated by Django 3.1.4 on 2020-12-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, null=True)),
                ('subtitle', models.CharField(max_length=90, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=90, null=True)),
                ('numberofclass', models.IntegerField(default='0')),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('metakeywords', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=90, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('metakeywords', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, null=True)),
                ('price', models.IntegerField(default='0')),
                ('minimumregisterprice', models.IntegerField(default='0')),
                ('numberofactivedays', models.IntegerField(default='0')),
                ('numberofclass', models.IntegerField(default='0')),
                ('style', models.CharField(max_length=90, null=True)),
                ('introduction', models.TextField(max_length=100, null=True)),
                ('video_url', models.CharField(max_length=90, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.category')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.level')),
            ],
        ),
    ]
