# Generated by Django 3.1.4 on 2020-12-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='numberofclass',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.category'),
        ),
        migrations.AlterField(
            model_name='program',
            name='minimumregisterprice',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='numberofactivedays',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='numberofclass',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
