# Generated by Django 3.1.4 on 2020-12-16 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20201216_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.level'),
        ),
    ]
