# Generated by Django 3.1.4 on 2020-12-18 04:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20201216_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
