# Generated by Django 3.1.4 on 2020-12-18 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0005_auto_20201218_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default='0', null=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('NotPaid', 'NotPaid')], max_length=90, null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('categorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.category')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
