# Generated by Django 3.1.1 on 2020-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_auto_20201219_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
