# Generated by Django 3.1.1 on 2020-12-30 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_auto_20201226_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='minimumregisterprice',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='numberofactivedays',
            new_name='video_duration',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
