# Generated by Django 3.1.1 on 2021-01-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_auto_20201230_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='categorid',
            new_name='categoryid',
        ),
        migrations.AddField(
            model_name='category',
            name='validity',
            field=models.IntegerField(default='30', null=True),
        ),
    ]
