# Generated by Django 3.1.1 on 2021-01-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_auto_20210102_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-day']},
        ),
    ]
