# Generated by Django 3.1.1 on 2021-01-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_auto_20210104_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['day']},
        ),
    ]
