# Generated by Django 3.1.1 on 2021-01-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_auto_20210104_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.category'),
        ),
    ]
