# Generated by Django 3.1.1 on 2021-04-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_auto_20210112_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='introduction',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
