# Generated by Django 3.2.3 on 2021-10-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_auto_20210423_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='SubscriptionValidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
