# Generated by Django 3.2.3 on 2021-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_auto_20211014_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
