# Generated by Django 3.1.1 on 2020-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20201213_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
