# Generated by Django 3.1.1 on 2020-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201213_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
