# Generated by Django 3.1.1 on 2020-12-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20201213_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='Accepted', max_length=50, null=True),
        ),
    ]
