# Generated by Django 3.1.1 on 2020-12-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_appoinment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Subscriber', 'Subscriber')], default='Accepted', max_length=50, null=True),
        ),
    ]
