# Generated by Django 3.1.1 on 2020-12-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
