# Generated by Django 3.1.1 on 2020-12-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20201215_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Subscriber', 'Subscriber')], max_length=50, null=True),
        ),
    ]
