# Generated by Django 3.1.1 on 2020-12-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20201215_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Subscriber', 'Subscriber')], default='Registered', max_length=50, null=True),
        ),
    ]
