# Generated by Django 3.1.1 on 2021-01-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20201216_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='order_id',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='signature',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
