# Generated by Django 3.1.1 on 2021-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20210105_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
