# Generated by Django 3.1.1 on 2021-01-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20210105_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='amount',
            field=models.IntegerField(blank=True, default='100', null=True),
        ),
    ]
