# Generated by Django 3.1.1 on 2021-04-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_appoinment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
