# Generated by Django 3.1.1 on 2021-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20210423_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('pending', 'pending')], max_length=50, null=True),
        ),
    ]
